version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run:
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: npm run lint
      - run:
          command: npm test
      - run:
          command: npm run semantic-release | true
          when: on_success
